"""
Created on 10/25/20

@author: giovannivignone
"""
import requests
import json
import re
import time


def Findproduct(keywords,dotcomesitelink,needed_size,monitor_delay):
    """This function takes keywords and a json scraping link and a
    site link and returns the productlink and id"""
    needed_size = str(needed_size)
    keyword_list = re.findall("[a-zA-Z]+",keywords)
    scrape = dotcomesitelink + "/products.json"
    product = {}
    while len(product) == 0:
        r = requests.get(scrape)
        products = json.loads(r.text)['products']
        print("---------Monitoring for product----------")
        for prod in products:
            name = prod["title"]
            count = 0
            for w in keyword_list:
                if w.lower() in name.lower():
                    count += 1
            if count == len(keyword_list):
                variants = prod["variants"]
                sizes = {}
                for varr in variants:
                    if varr["available"] == True:
                        size = varr["title"]
                        identifier = varr["id"]
                        sizes[size] = identifier
                if needed_size in sizes:
                    print("Available sizes=", sizes)
                    link = dotcomesitelink + "/products/" + prod["handle"]
                    product[name] = [link, needed_size, sizes[needed_size]]
                    print(product)
                    return (product[name][0],product[name][-1])
                else:
                    print(name, " OOS retrying")
        time.sleep(monitor_delay)






if __name__ == '__main__':
    product = (Findproduct("+nike",'https://www.shoepalace.com',"11",4))
    pass
